# Generated by Django 4.2.6 on 2023-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='danLevel',
            field=models.IntegerField(default=0),
        ),
    ]
